f_beta: 0.82
lr_scheduler:
  name: StepLR
  parameters:
    gamma: 0.1491746734976624
    step_size: 2
optimizer:
  name: SGD
  parameters:
    lr: 0.004668558203562765
    momentum: 0.0
    weight_decay: 0.0004
